# Use postgres/example user/password credentials
version: '3.1'

services:

  app:
    build: ./app
    restart: unless-stopped
    ports:
      - 5050:5050

  db:
    image: postgres:16.0
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/data/ # https://stackoverflow.com/a/63824663
    volumes:
      - poc-data:/var/lib/postgresql/data # https://stackoverflow.com/a/41650891

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080

volumes:
  poc-data:
